server:
  port: 8080
spring:
  application:
    name: "arquitecturaLimpia"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://yhomira:yhomira@proyectos.cw1oh.mongodb.net/BibliotecaReactiva?retryWrites=true&w=majority"
